spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/adoption_platform
spring.datasource.username=adoption_user
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true